# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProfile',
            fields=[
                ('profile_id', models.CharField(default='4d4cb26ffd5e41d886c3cc94fb1a769e', max_length=64, primary_key=True, serialize=False)),
                ('study_status', models.CharField(blank=True, choices=[('U', 'Undergraduate'), ('P', 'Postgraduate')], max_length=32, null=True, verbose_name='Study Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
