# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UserGroup',
                'verbose_name_plural': 'UserGroups',
            },
        ),
        migrations.RemoveField(
            model_name='basicprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='profile_id',
            field=models.CharField(default='e388ca9c36d2433fb81aaa34c7f3848c', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='user_group',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserGroup'),
            preserve_default=False,
        ),
    ]
