# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BadgeId', models.CharField(max_length=20)),
                ('BadgeStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BageInfoId', models.CharField(max_length=20)),
                ('BageName', models.CharField(max_length=40)),
                ('Deprecation', models.TextField()),
                ('Relatiom', models.CharField(max_length=50)),
                ('Imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncentiveId', models.CharField(max_length=20)),
                ('IncentiveType', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(blank=True, default='', max_length=100)),
                ('StaffId', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventId', models.CharField(max_length=20)),
                ('EvenType', models.CharField(max_length=20)),
                ('EventDate', models.DateTimeField()),
                ('EventContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointsId', models.CharField(max_length=20)),
                ('CurrentPoints', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('StaffId', models.CharField(blank=True, default='', max_length=100)),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('ModifyDate', models.DateTimeField()),
                ('Description', models.TextField()),
                ('UserProfileYear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('studentId', models.CharField(blank=True, default='', max_length=100)),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('Degree', models.CharField(max_length=30)),
                ('Discipline', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('residentStatus', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('graduation_year', models.CharField(max_length=30)),
                ('YearOfStudy', models.CharField(max_length=10)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserEventId', models.CharField(max_length=20)),
                ('UserEventType', models.CharField(max_length=20)),
                ('UserEventDate', models.DateTimeField()),
                ('UserEventContent', models.TextField()),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFFU.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileYear', models.CharField(max_length=20)),
                ('ProfileType', models.CharField(max_length=20)),
                ('NetworkTree', models.CharField(max_length=30)),
                ('SkillTree', models.CharField(max_length=30)),
                ('ExperienceTree', models.CharField(max_length=30)),
                ('PreparationTree', models.CharField(max_length=30)),
                ('Network', models.TextField()),
                ('Skill', models.TextField()),
                ('Experience', models.TextField()),
                ('Preparation', models.TextField()),
                ('Notes', models.TextField()),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFFU.Student')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFFU.Student'),
        ),
        migrations.AddField(
            model_name='badge',
            name='BadgeInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PFFU.BadgeInfo'),
        ),
    ]
